name: Scheduled Nightly Build

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  find_latest_commit:
    name: Find latest commit
    runs-on: ubuntu-latest
    outputs:
      build_ref: ${{ steps.check.outputs.build_ref }}
      release_tag: ${{ steps.check.outputs.release_tag }}
      release_body: ${{ steps.check.outputs.release_body }}
    steps:
      - name: Check releases
        id: check
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          # Get latest commit SHA
          LATEST_SHA=$(git rev-parse HEAD)
          COMMIT_MSG=$(git log -1 --pretty=%B)
          REPO_URL="$GITHUB_SERVER_URL/$GITHUB_REPOSITORY"
          COMMIT_URL="$REPO_URL/commit/$LATEST_SHA"
          SHA=${LATEST_SHA:0:8}
          
          echo "Building pre-release from local repository commit $SHA"
          echo "build_ref=$LATEST_SHA" >> $GITHUB_OUTPUT
          echo "release_tag=$(date +'%m-%d-%Y')" >> $GITHUB_OUTPUT
          echo "release_body=Built from local repository commit [$SHA]($COMMIT_URL):\n$COMMIT_MSG" >> $GITHUB_OUTPUT

  trigger_build:
    name: Build
    needs: find_latest_commit
    uses: ./.github/workflows/build.yml
    with:
      ref: ${{ needs.find_latest_commit.outputs.build_ref }}

  trigger_release:
    name: Release
    needs: [find_latest_commit, trigger_build]
    uses: ./.github/workflows/release.yml
    with:
      is_prerelease: true
      release_tag: ${{ needs.find_latest_commit.outputs.release_tag }}
      release_body: ${{ needs.find_latest_commit.outputs.release_body }}
    permissions:
      contents: write